typography_spectrum: 0.10979085718281567
color:
  brandStrength: 0.576021522982046
  lightness: 0.6579470250289887
  saturation: 0.8838497092947364
  rhythmicContrast: 0.7231475759763271
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.4239709808025509
author:
  name: Neil Wilkins
  email: neil@vmcg.co.uk
  url: neilwilkins.co.uk
name: Neil Wilkins
title: Neil Wilkins
description: '"You are exactly what you think you are"'
