typography_spectrum: 0.13849928975105286
color:
  brandStrength: 0.2211588704958558
  lightness: 0.29381944704800844
  saturation: 0.4187869883608073
  rhythmicContrast: 0.6385442896280438
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
layout_spectrum: 0.9764380238484591
analytics:
  google: UA-81861183-1
author:
  name: Neil Wilkins
  email: neil@vmcg.co.uk
  url: neilwilkins.co.uk
name: Neil Wilkins
navigation:
  - name: 'Viper Marketing : marketing services'
    url: 'http://www.vmcg.co.uk'
    type: external
  - name: Growth Hacking
    url: 'http://www.venturity.co.uk'
    type: external
title: Neil Wilkins
description: '"You are exactly who you think you are"'
