layout_spectrum: 0.27965741767548025
typography_spectrum: 0.30876590055413544
color:
  brandStrength: 0.04853490018285811
  lightness: 0.953734734095633
  saturation: 0.5866156439296901
  rhythmicContrast: 0.8206163716968149
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
analytics:
  google: UA-81861183-1
author:
  name: Neil Wilkins
  email: neil@vmcg.co.uk
  url: neilwilkins.co.uk
name: Neil Wilkins
navigation:
  - name: Marketing Services
    url: 'http://www.vmcg.co.uk'
    type: external
  - name: Growth Hacking
    url: 'http://www.venturity.co.uk'
    type: external
title: Neil Wilkins
description: '"You are exactly who you think you are"'
